apiVersion: v1
kind: Secret
metadata:
  name: fortiaigate-tls-secret
  namespace: fortiaigate
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFmTCCA4GgAwIBAgIUCjN6/qTPTfqQSrzu+8N4MgIciSMwDQYJKoZIhvcNAQEL
    BQAwNDEyMDAGA1UEAwwpZm9ydGlhaWdhdGUuZm9ydGlhaWdhdGUuc3ZjLmNsdXN0
    ZXIubG9jYWwwHhcNMjYwMzMxMTgxMzA1WhcNMzYwMzI4MTgxMzA1WjA0MTIwMAYD
    VQQDDClmb3J0aWFpZ2F0ZS5mb3J0aWFpZ2F0ZS5zdmMuY2x1c3Rlci5sb2NhbDCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANgtQ8u96Uv6mX+Rp1N2wg1o
    iUw3XFyD4gBuxQNR6bnPy7dK7qAOiBEzF+oYIxriQZF1YSWtmu85tR7oFV2yEBIh
    /EqHvmFNTHHuv+qFHqY17uLY1pOzeQ7BjNKsUMgWhZHEg+i1pTdxCr3bv2tIFL3J
    Ri62+rrONgBppc/dMG3FXFoz3PsM7OCJ0Is552Oh7AU1fG/VQlRUnrflVyKe2Y0U
    CM21wxwI2uRyzBvkDcRYPKLVL6dv8ijLMKWvrfnirw7K6ivjvSHHkJhZ7RbE9SOS
    uErzGyRqX5QN9aPKKL0TLMuOYTtoABZ3zeZ3puH9HhemlCttV00sRS9atNzJXPuT
    TXaAR7xmfw3dBtL54zgNPeSff/BJ0ZWkgtNj1maJ7Efzygdemxm0YAIEH9MNAIKW
    aNwh+t4YC17HO+yP4xn93jZSaC6uS+xbX+MqlmDFOEGTi85P03JeV6OB0BcKENVW
    AdSEgppk+ffL04qUdZa/W9lInuru5eXGhsEXAr5or7r8H10VmESif9KnUHejE1tJ
    6UISnZm/2fRCQsGfYhiWilTBCRuPHgb3OExSY8VyYEjkDiioPZyKxxJ0UpD2/40i
    00eoA8ElPM4EsKxDx7dN/a1rLP3rAsy8/dmACiTgqtT9j2ZmrM+1iR02wYI/5JlZ
    JceBcLfoxfQGO8h/DB5XAgMBAAGjgaIwgZ8wHQYDVR0OBBYEFKc/lxMQ6VaEJLfY
    RUgTEGCSEt7pMB8GA1UdIwQYMBaAFKc/lxMQ6VaEJLfYRUgTEGCSEt7pMA8GA1Ud
    EwEB/wQFMAMBAf8wTAYDVR0RBEUwQ4ILZm9ydGlhaWdhdGWCKWZvcnRpYWlnYXRl
    LmZvcnRpYWlnYXRlLnN2Yy5jbHVzdGVyLmxvY2Fsgglsb2NhbGhvc3QwDQYJKoZI
    hvcNAQELBQADggIBALxJpoCWilgVlDO5ihx+TSqZ5nG+lmnlYTlccff4w8u2FVXf
    x5+7TjnS/eAqhCDLYdeqJztMHpoLsRk2VoZ5CNOauf4HBvO5Y1xOo2U9kJHKXnPY
    k0ZREccu+Rw0IRO3EQlC89XykXqWnrhy5OFMVA6uXOKU9FnYWt3yo0AicyUZNsLR
    OroHapT5yg0q++YST3cgzSUg1T/4fTNACXVI7Y/dUoplfcCJgu9RGEY0wU/v/izv
    kUWSAIo1drPMIDoC20c8aY3tZNGBq0ZOIZPvD+Ebiqgj+zicFiolBc4/aXz8tVEa
    0aDL2cGtGF/liEBqtidUtBaqE0CryNRCcbOd8PB1BjtV+wSKyfYVEfmKBSLAHoeY
    mcw6ryN8MRwwL0qAG1WASEQheeq1Z/ShlSAP8WYtxrs2w6pURoeBFOJX/LLIMpx3
    y8qZqpo/Hw3RIWUfItnsdIspR9iPKw4f3doY98jYLtPRj+6C9rtKjZUWITEUyoGe
    EjWLKaNlrEyRWknAXiGw9xoX5xrT4aRFpDh9duPaNQzQIAKtm1Z5/X76RjHC2Q6A
    Anh3pJCGla/P42Z8wHNeIyCD+E5kba7k3/PJwAVuCxtt1i2DXzkLaAUUt2WCAf/9
    zPbHhzlQKzOpY1qkuACoASOajbhylcvQ0CuPMIxODhM9hQBWuCRP+4Zv7Sah
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQDYLUPLvelL+pl/
    kadTdsINaIlMN1xcg+IAbsUDUem5z8u3Su6gDogRMxfqGCMa4kGRdWElrZrvObUe
    6BVdshASIfxKh75hTUxx7r/qhR6mNe7i2NaTs3kOwYzSrFDIFoWRxIPotaU3cQq9
    279rSBS9yUYutvq6zjYAaaXP3TBtxVxaM9z7DOzgidCLOedjoewFNXxv1UJUVJ63
    5VcintmNFAjNtcMcCNrkcswb5A3EWDyi1S+nb/IoyzClr6354q8Oyuor470hx5CY
    We0WxPUjkrhK8xskal+UDfWjyii9EyzLjmE7aAAWd83md6bh/R4XppQrbVdNLEUv
    WrTcyVz7k012gEe8Zn8N3QbS+eM4DT3kn3/wSdGVpILTY9ZmiexH88oHXpsZtGAC
    BB/TDQCClmjcIfreGAtexzvsj+MZ/d42UmgurkvsW1/jKpZgxThBk4vOT9NyXlej
    gdAXChDVVgHUhIKaZPn3y9OKlHWWv1vZSJ7q7uXlxobBFwK+aK+6/B9dFZhEon/S
    p1B3oxNbSelCEp2Zv9n0QkLBn2IYlopUwQkbjx4G9zhMUmPFcmBI5A4oqD2ciscS
    dFKQ9v+NItNHqAPBJTzOBLCsQ8e3Tf2tayz96wLMvP3ZgAok4KrU/Y9mZqzPtYkd
    NsGCP+SZWSXHgXC36MX0BjvIfwweVwIDAQABAoICAAGpK12r2lh+luJPhKkT/v6q
    YG+o9zkwvDJDp5jUbsbCLW79kOLC6dG0AkmGoPJqbZWIANSQxmFzIIyZvNxI622w
    PCd4boKB3QX9DxVmq2sce/bbMp7U4Ke33fSaZU58Oc96YocNqjTIVgxKXWieF6az
    nqnqNvfrcKfFKAR2TxJw0zpQLrDxEvrQpD0Fl10BF/acSBX13foW4ldIWEiITuSS
    FFU8QcD74m6h4SaPtHlfMiwQFjsjlYkxsnB7bos+bhjffzgSGlhhl59MBZHItpds
    36SXxIwdkxlomAwHmBOHy67Oq7mQnXuOtRLBtZMD5lDJM1c4ElUh83AfMseFdoTm
    qWqOuOi+HzsTGPPxX/o6JYBbCEavaMyuQlXxsjc5LUvoB2lm0j5RiN+A9rGHkgi+
    lx9etKsGr6tg24oUG1zEAKbDQ2Vu6DfICdWHvtC66kYOkMrk366Q1r2D/1+gwRqW
    RGnt9GUFkFf9wbeHV2926ctwA+qLUohP5XE9Ohz0aYxs6a4iC4V4+p6ZU6KiFnbf
    X1MC3cEHyVh+IZOpRCcGQ80GT+21i3KdFw2dhzkiY3USWekwPQfE1l2vWS9zOl0f
    bOeLP6nOjv9OTb0oiFbmQ8MWOIH4IsYIFkdQ6WynstLvYp85mVndcrSthUvX4M4B
    GS0Ic2NXK6bwEbBnrvGtAoIBAQDja1zDx60w+wYAaFUcdcUU3Q3VYeD1kXNEsW8/
    o3z9G2D/VYDugFBdgc4nA0WB+kPGBJLPEJ1sLceNO+BeE+ID/puDNyn9ppU57wzx
    BaZUGzmYeuYllAB61ExAtksffnJICH+ASkTn8meTZnzrBEEWtB8FjmY41PG7dTn+
    2eaw0SKyERf25fnvPgQjYbsw/WeCMXpRiKm4nW1ht6YGjRIxCt3Nw0+gPlSPdsKo
    7QZpsrQAcrezjhB51x4XOFgCbfInRKjngAULDhLhws/ZzZZN/y/9KKXOWwG1ajCZ
    902OFgHrUygg5zYoaEgNe7tIZ5JljXeQbPRaY0AtssZSUyvrAoIBAQDzWDOYrA6v
    TQTmAuNi7wy16Rmh4jUdF6rcYKsNffLBrwxp/11j1ArJbIvoMmtX5MhItKPp5xWH
    KI2NbSQEVYMKL4ydyrjHMdQTp3WUp57ebR/1jLuXhiYe2FMQ2vC2l85msk33FwsF
    3loFOMsGwoeQHkUpt4LPcwOWQH1ZD5UZfQ6FfVdPLJAaK2VLoXk30ddj9qHHTW1W
    ncBXvMlPM/SkoiVJuzxP6AFy210hys+AXooOEiRcCs7+T4ez24hQ8gflbRQfvexK
    lYFGf0teyuDiKw3V8fGWjstazavaQdZ/VbW6wST+CwUwTUHaOSKm00SFrhvDCnrR
    wfrqRCC++dhFAoIBAAmss5GQmQmQZDz4M0a2q9+rV79QHqXTvjeZ5MWsStDprUKv
    fICo7MJNl1uJhBd3chKmdyhf6JKFkAuuFGlsJx1MY4k9e4fS4l5IkSBfwSeq0NRv
    xgKrPSn8hhHqr19znaD625G1lyDW6xkWLxJAaBRzLS6rVCXuySnUXtc8pde3zeYN
    XBugxPUsijiHG9OFtDWRrUZyreWwrMqPaXy126RCdhUezfBfNnGz96wACVnNxGKQ
    fsggrwq/4APU3cmcq8SH4zeV9qD1xE/eXcFCQbanuH7oj8UrkfMJxW+HWcFFpmdA
    bmCX9XHandYVAW6fGVdAoWl/eRWvSzemd1FhQGkCggEAPyYBZbooqWc0QTg4p+Df
    DInsI+1e2SjeJwhS+1JW39o8P3mMU66gCftIJz6GSq3NJ8jwzG8yT/u/GBddhF5o
    fgku1XfZEaAlp+AKDESfXps08vTNbZnbZJ/AlpwqYUftwQq+XsO1EZXNCJPfY+ax
    ZT3lttivcoQnRyN/I9B+YbnpPcz0DlDDKHdgdwr1OP4UhhVnkB/QouyXEG2mVA5o
    ixykzohvM1FCpvq0JWPLC0X9T393vgb0Bly/G3Z53n+gevIeicowen5nqNK5zWSa
    jTadBYsepXJy5SKAWUhCkJK+cTNUFTTo6Mrzrtyq2F305zfybl/W1X4gThDV6plN
    fQKCAQBQDeXccnWyKXMnRSYqWkTil18dYYyEq4lRWbfXD9/mQGsICc1cnasyUi7z
    klpfU54A+KXaurBx31sctCEXtiHQ3cSP8xdtwt1A/XNhMq7+vtC9tRQjyp0j8+oZ
    +kL5MgFEIYPPJkEVS6vKgGR1E+EtHJAXmjnTApor8dSjTVjCJ5teQXfKUwxMwGVf
    gMH6ySIqcUQRSTKOD99sL6WoVXs8blN1Y/GgWRTn98fMzkE/v8O2cVIFfpsp2tcI
    nJzwQXQLDzQ4gaTM2N3Zv0t3y6MT8L/uhR7tsXGHTo3eyfULHR1aJnDEAWrtQzAJ
    +/xb//VWVWMUpZHyCyJ853pqTUwW
    -----END PRIVATE KEY-----
