apiVersion: v1
kind: Secret
metadata:
  name: fortiaigate-tls-secret
  namespace: fortiaigate
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YOUR_CERTIFICATE
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_YOUR_PRIVATE_KEY
    -----END PRIVATE KEY-----
