{{- if and (eq (include "fortiaigate.shouldMountTlsSecret" .) "true") (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fortiaigate.tlsSecretName" . }}
  labels:
    app.kubernetes.io/name: fortiaigate
    app.kubernetes.io/part-of: fortiaigate-platform
    app.kubernetes.io/managed-by: helm
type: kubernetes.io/tls
data:
{{- if and .Values.tls.certData .Values.tls.keyData }}
  tls.crt: {{ .Values.tls.certData | b64enc }}
  tls.key: {{ .Values.tls.keyData | b64enc }}
{{- else }}
  tls.crt: {{ tpl (.Files.Get .Values.tls.cert) $ | b64enc }}
  tls.key: {{ tpl (.Files.Get .Values.tls.key) $ | b64enc }}
{{- end }}
{{- end }}
