# Update these values to match your cluster before installation.
clusterName: fortiaigate-eks
region: us-east-1
vpcId: vpc-05521470b77d5955a

serviceAccount:
  create: false
  name: aws-load-balancer-controller

replicaCount: 2
